<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategoriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('categories')->insert([
            ['full_name' => 'Алюминиевые ограждения','name' => 'Алюминиевые ограждения','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>1 ],
            ['full_name' => 'Алюминиевые ограждения','name' => 'Алюминиевые ограждения','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>2 ],
            ['full_name' => 'Арматура','name' => 'Арматура','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>3 ],
            ['full_name' => 'Арматура воздуховодов','name' => 'Арматура воздуховодов','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>4 ],
            ['full_name' => 'Арматура трубопроводов (краны, клапаны и т.п)','name' => 'Арматура трубопроводов (краны, клапаны и т.п)','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>5 ],
            ['full_name' => 'Бак разрыва струи','name' => 'Бак разрыва струи','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>6 ],
            ['full_name' => 'Балки','name' => 'Балки','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>7 ],
            ['full_name' => 'Бетонная подготовка','name' => 'Бетонная подготовка','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>8 ],
            ['full_name' => 'Бетонная подготовка','name' => 'Бетонная подготовка','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>9 ],
            ['full_name' => 'Бетонная подготовка','name' => 'Бетонная подготовка','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>10 ],
            ['full_name' => 'Блок домофона','name' => 'Блок домофона','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>11 ],
            ['full_name' => 'Блок домофона','name' => 'Блок домофона','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>12 ],
            ['full_name' => 'Блок домофона','name' => 'Блок домофона','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>13 ],
            ['full_name' => 'Вентиляционные блоки','name' => 'Вентиляционные блоки','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>14 ],
            ['full_name' => 'Вентиляционный клапан','name' => 'Вентиляционный клапан','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>15 ],
            ['full_name' => 'Видеокамера','name' => 'Видеокамера','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>16 ],
            ['full_name' => 'Видеокамера','name' => 'Видеокамера','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>17 ],
            ['full_name' => 'Видеокамера','name' => 'Видеокамера','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>18 ],
            ['full_name' => 'Витражи','name' => 'Витражи','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>19 ],
            ['full_name' => 'Витражи','name' => 'Витражи','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>20 ],
            ['full_name' => 'Водоотводный лоток','name' => 'Водоотводный лоток','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>21 ],
            ['full_name' => 'Водоотводный лоток','name' => 'Водоотводный лоток','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>22 ],
            ['full_name' => 'Воздуховоды','name' => 'Воздуховоды','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>23 ],
            ['full_name' => 'Воздушный демпфер','name' => 'Воздушный демпфер','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>24 ],
            ['full_name' => 'Выключатели','name' => 'Выключатели','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>25 ],
            ['full_name' => 'Выключатели','name' => 'Выключатели','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>26 ],
            ['full_name' => 'Выключатели','name' => 'Выключатели','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>27 ],
            ['full_name' => 'Гидроизоляция фундаментов','name' => 'Гидроизоляция фундаментов','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>28 ],
            ['full_name' => 'Двери','name' => 'Двери','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>29 ],
            ['full_name' => 'Двери','name' => 'Двери','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>30 ],
            ['full_name' => 'Диффузор вытяжной','name' => 'Диффузор вытяжной','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>31 ],
            ['full_name' => 'Закладные детали','name' => 'Закладные детали','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>32 ],
            ['full_name' => 'Изоляция','name' => 'Изоляция','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>33 ],
            ['full_name' => 'Кабели','name' => 'Кабели','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>34 ],
            ['full_name' => 'Кабели','name' => 'Кабели','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>35 ],
            ['full_name' => 'Кабели','name' => 'Кабели','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>36 ],
            ['full_name' => 'Кабельные лотки','name' => 'Кабельные лотки','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>37 ],
            ['full_name' => 'Кабельные лотки','name' => 'Кабельные лотки','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>38 ],
            ['full_name' => 'Кабельные лотки','name' => 'Кабельные лотки','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>39 ],
            ['full_name' => 'Клиновая задвижки','name' => 'Клиновая задвижки','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>40 ],
            ['full_name' => 'Козырьки','name' => 'Козырьки','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>41 ],
            ['full_name' => 'Козырьки','name' => 'Козырьки','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>42 ],
            ['full_name' => 'Колонны монолитные','name' => 'Колонны монолитные','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>43 ],
            ['full_name' => 'Колонны сборные','name' => 'Колонны сборные','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>44 ],
            ['full_name' => 'Колонны сборные','name' => 'Колонны сборные','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>45 ],
            ['full_name' => 'Колонны сборные','name' => 'Колонны сборные','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>46 ],
            ['full_name' => 'Корзина кондиционера','name' => 'Корзина кондиционера','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>47 ],
            ['full_name' => 'Корзина кондиционера','name' => 'Корзина кондиционера','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>48 ],
            ['full_name' => 'Короба','name' => 'Короба','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>49 ],
            ['full_name' => 'Короба','name' => 'Короба','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>50 ],
            ['full_name' => 'Короба','name' => 'Короба','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>51 ],
            ['full_name' => 'Кровля','name' => 'Кровля','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>52 ],
            ['full_name' => 'Кровля','name' => 'Кровля','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>53 ],
            ['full_name' => 'Лестничные марши','name' => 'Лестничные марши','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>54 ],
            ['full_name' => 'Лестничные марши из сборных ступеней','name' => 'Лестничные марши из сборных ступеней','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>55 ],
            ['full_name' => 'Лестничные марши монолитные','name' => 'Лестничные марши монолитные','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>56 ],
            ['full_name' => 'Лестничные марши сборные','name' => 'Лестничные марши сборные','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>57 ],
            ['full_name' => 'Лестничные марши сборные','name' => 'Лестничные марши сборные','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>58 ],
            ['full_name' => 'Лестничные марши сборные','name' => 'Лестничные марши сборные','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>59 ],
            ['full_name' => 'Лифтовые шахты','name' => 'Лифтовые шахты','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>60 ],
            ['full_name' => 'Металлическая маршевая лестница','name' => 'Металлическая маршевая лестница','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>61 ],
            ['full_name' => 'Металлическая маршевая лестница','name' => 'Металлическая маршевая лестница','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>62 ],
            ['full_name' => 'Накрывочные элементы парапетов','name' => 'Накрывочные элементы парапетов','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>63 ],
            ['full_name' => 'Накрывочные элементы парапетов','name' => 'Накрывочные элементы парапетов','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>64 ],
            ['full_name' => 'Насос дренажный','name' => 'Насос дренажный','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>65 ],
            ['full_name' => 'Оборудование','name' => 'Оборудование','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>66 ],
            ['full_name' => 'Оборудование','name' => 'Оборудование','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>67 ],
            ['full_name' => 'Оборудование','name' => 'Оборудование','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>68 ],
            ['full_name' => 'Оборудование','name' => 'Оборудование','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>69 ],
            ['full_name' => 'Оборудование пожарного крана','name' => 'Оборудование пожарного крана','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>70 ],
            ['full_name' => 'Ограждения','name' => 'Ограждения','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>71 ],
            ['full_name' => 'Ограждения','name' => 'Ограждения','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>72 ],
            ['full_name' => 'Окна','name' => 'Окна','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>73 ],
            ['full_name' => 'Окна','name' => 'Окна','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>74 ],
            ['full_name' => 'Осветительные приборы','name' => 'Осветительные приборы','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>75 ],
            ['full_name' => 'Осветительные приборы','name' => 'Осветительные приборы','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>76 ],
            ['full_name' => 'Осветительные приборы','name' => 'Осветительные приборы','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>77 ],
            ['full_name' => 'Отверстия','name' => 'Отверстия','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>78 ],
            ['full_name' => 'Отверстия','name' => 'Отверстия','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>79 ],
            ['full_name' => 'Отверстия','name' => 'Отверстия','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>80 ],
            ['full_name' => 'Отделка стен, колонн, полов, откосов и потолков','name' => 'Отделка стен, колонн, полов, откосов и потолков','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>81 ],
            ['full_name' => 'Отделка стен, колонн, полов, откосов и потолков','name' => 'Отделка стен, колонн, полов, откосов и потолков','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>82 ],
            ['full_name' => 'Откосы','name' => 'Откосы','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>83 ],
            ['full_name' => 'Откосы','name' => 'Откосы','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>84 ],
            ['full_name' => 'Отмостка','name' => 'Отмостка','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>85 ],
            ['full_name' => 'Отмостка','name' => 'Отмостка','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>86 ],
            ['full_name' => 'Отопительные приборы','name' => 'Отопительные приборы','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>87 ],
            ['full_name' => 'Охранная сигнализация','name' => 'Охранная сигнализация','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>88 ],
            ['full_name' => 'Охранная сигнализация','name' => 'Охранная сигнализация','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>89 ],
            ['full_name' => 'Охранная сигнализация','name' => 'Охранная сигнализация','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>90 ],
            ['full_name' => 'Парапеты','name' => 'Парапеты','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>91 ],
            ['full_name' => 'Перегородки','name' => 'Перегородки','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>92 ],
            ['full_name' => 'Перегородки','name' => 'Перегородки','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>93 ],
            ['full_name' => 'Перекрытия','name' => 'Перекрытия','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>94 ],
            ['full_name' => 'Перекрытия','name' => 'Перекрытия','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>95 ],
            ['full_name' => 'Перемычки','name' => 'Перемычки','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>96 ],
            ['full_name' => 'Перемычки','name' => 'Перемычки','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>97 ],
            ['full_name' => 'Пилоны','name' => 'Пилоны','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>98 ],
            ['full_name' => 'Плинтуса в помещениях МОП','name' => 'Плинтуса в помещениях МОП','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>99 ],
            ['full_name' => 'Плинтуса в помещениях МОП','name' => 'Плинтуса в помещениях МОП','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>100 ],
            ['full_name' => 'Плиты монолитные','name' => 'Плиты монолитные','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>101 ],
            ['full_name' => 'Плиты сборные','name' => 'Плиты сборные','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>102 ],
            ['full_name' => 'Плиты сборные','name' => 'Плиты сборные','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>103 ],
            ['full_name' => 'Плиты сборные','name' => 'Плиты сборные','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>104 ],
            ['full_name' => 'Подоконные доски','name' => 'Подоконные доски','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>105 ],
            ['full_name' => 'Подоконные доски','name' => 'Подоконные доски','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>106 ],
            ['full_name' => 'Пожарная сигнализация','name' => 'Пожарная сигнализация','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>107 ],
            ['full_name' => 'Пожарная сигнализация','name' => 'Пожарная сигнализация','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>108 ],
            ['full_name' => 'Пожарная сигнализация','name' => 'Пожарная сигнализация','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>109 ],
            ['full_name' => 'Приямки','name' => 'Приямки','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>110 ],
            ['full_name' => 'Радиаторы','name' => 'Радиаторы','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>111 ],
            ['full_name' => 'Решетка вытяжная','name' => 'Решетка вытяжная','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>112 ],
            ['full_name' => 'Сантехнические приборы (Умывальник, унитаз, ванная и т.д.)','name' => 'Сантехнические приборы (Умывальник, унитаз, ванная и т.д.)','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>113 ],
            ['full_name' => 'Сборные изделия','name' => 'Сборные изделия','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>114 ],
            ['full_name' => 'Сваи','name' => 'Сваи','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>115 ],
            ['full_name' => 'Сливы','name' => 'Сливы','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>116 ],
            ['full_name' => 'Сливы','name' => 'Сливы','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>117 ],
            ['full_name' => 'Соединительные детали','name' => 'Соединительные детали','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>118 ],
            ['full_name' => 'Соединительные детали','name' => 'Соединительные детали','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>119 ],
            ['full_name' => 'Спринклеры','name' => 'Спринклеры','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>120 ],
            ['full_name' => 'Стены','name' => 'Стены','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>121 ],
            ['full_name' => 'Стены панельные','name' => 'Стены панельные','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>122 ],
            ['full_name' => 'Стены панельные','name' => 'Стены панельные','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>123 ],
            ['full_name' => 'Стремянки','name' => 'Стремянки','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>124 ],
            ['full_name' => 'Стремянки','name' => 'Стремянки','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>125 ],
            ['full_name' => 'Счетчики','name' => 'Счетчики','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>126 ],
            ['full_name' => 'Счетчики воды','name' => 'Счетчики воды','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>127 ],
            ['full_name' => 'Трубы','name' => 'Трубы','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>128 ],
            ['full_name' => 'Трубы','name' => 'Трубы','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>129 ],
            ['full_name' => 'Устройство вызова и оповещения','name' => 'Устройство вызова и оповещения','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>130 ],
            ['full_name' => 'Устройство вызова и оповещения','name' => 'Устройство вызова и оповещения','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>131 ],
            ['full_name' => 'Устройство вызова и оповещения','name' => 'Устройство вызова и оповещения','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>132 ],
            ['full_name' => 'Устройство связи','name' => 'Устройство связи','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>133 ],
            ['full_name' => 'Устройство связи','name' => 'Устройство связи','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>134 ],
            ['full_name' => 'Устройство связи','name' => 'Устройство связи','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>135 ],
            ['full_name' => 'Утеплители','name' => 'Утеплители','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>136 ],
            ['full_name' => 'Утеплители','name' => 'Утеплители','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>137 ],
            ['full_name' => 'Фасадная часть','name' => 'Фасадная часть','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>138 ],
            ['full_name' => 'Фасадная часть','name' => 'Фасадная часть','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>139 ],
            ['full_name' => 'Фундаменты ленточные','name' => 'Фундаменты ленточные','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>140 ],
            ['full_name' => 'Фундаменты ленточные','name' => 'Фундаменты ленточные','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>141 ],
            ['full_name' => 'Фундаменты ленточные','name' => 'Фундаменты ленточные','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>142 ],
            ['full_name' => 'Фундаменты плитные','name' => 'Фундаменты плитные','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>143 ],
            ['full_name' => 'Фундаменты свайные','name' => 'Фундаменты свайные','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>144 ],
            ['full_name' => 'Фундаменты столбчатые','name' => 'Фундаменты столбчатые','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>145 ],
            ['full_name' => 'Щебеночная подготовка','name' => 'Щебеночная подготовка','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>146 ],
            ['full_name' => 'Щебеночная подготовка','name' => 'Щебеночная подготовка','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>147 ],
            ['full_name' => 'Щебеночная подготовка','name' => 'Щебеночная подготовка','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>148 ],
            ['full_name' => 'Щитки','name' => 'Щитки','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>149 ],
            ['full_name' => 'Щитки','name' => 'Щитки','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>150 ],
            ['full_name' => 'Щитки','name' => 'Щитки','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>151 ],
            ['full_name' => 'Электрические приборы','name' => 'Электрические приборы','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>152 ],
            ['full_name' => 'Электрические приборы','name' => 'Электрические приборы','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>153 ],
            ['full_name' => 'Электрические приборы','name' => 'Электрические приборы','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>154 ],
            ['full_name' => 'Электрооборудование','name' => 'Электрооборудование','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>155 ],
            ['full_name' => 'Электрооборудование','name' => 'Электрооборудование','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>156 ],
            ['full_name' => 'Электрооборудование','name' => 'Электрооборудование','created_at' => Carbon::now(),'updated_at' => Carbon::now(),'id'=>157 ],

        ]);
    }
}
