stages:
  - build
  - deploy

variables:
  DEPLOYMENT_NAME: backend
  REGISTRY_IMAGE: family-backend
  K8S_NAMESPACE: $PROD_K8S_NAMESPACE

.build:image:template: &build_definition
  stage: build
  image:
    name: registry.bi.group/custom-images/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - mkdir -p /kaniko/.docker
    - |
      cat << EOF > /kaniko/.docker/config.json
      {
        "auths": {
          "$REGISTRY_URL": {
            "auth": "$REGISTRY_TOKEN"
          }
        }
      }
      EOF
  script:
    - echo "$REGISTRY_URL/$K8S_NAMESPACE/$REGISTRY_IMAGE/$CI_COMMIT_BRANCH:$CI_COMMIT_SHORT_SHA"
    - >-
      /kaniko/executor
      --cache=true
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "$REGISTRY_URL/$K8S_NAMESPACE/$REGISTRY_IMAGE/$CI_COMMIT_BRANCH:$CI_COMMIT_SHORT_SHA"
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/ 

.deploy:template: &deploy_definition
  stage: deploy
  image: registry.bi.group/public/kubectl:gitlab-1.0.0
  script:
    - kubectl config set-cluster k8s --server="$K8S_SERVER" --insecure-skip-tls-verify=true
    - kubectl config set-credentials gitlab --token="$K8S_TOKEN"
    - kubectl config set-context default --cluster=k8s --user=gitlab --namespace="$K8S_NAMESPACE"
    - kubectl config use-context default
    - kubectl set image deployment/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=$REGISTRY_URL/$K8S_NAMESPACE/$REGISTRY_IMAGE/$CI_COMMIT_BRANCH:$CI_COMMIT_SHORT_SHA
  dependencies: []

.rules:testing:template: &rules_testing_definition
  resource_group: $CI_COMMIT_BRANCH
  rules:
    - if: $CI_COMMIT_BRANCH == "test"

.rules:production:template: &rules_production_definition
  resource_group: $CI_COMMIT_BRANCH
  rules:
    - if: $CI_COMMIT_BRANCH == "master"


build:testing:
  <<: *build_definition
  <<: *rules_testing_definition
  tags:
    - family-manager

build:production:
  <<: *build_definition
  <<: *rules_production_definition
  tags:
    - family-manager

deploy:testing:
  <<: *deploy_definition
  <<: *rules_testing_definition
  variables:
    K8S_SERVER: $TEST_K8S_SERVER
    K8S_TOKEN: $TEST_K8S_TOKEN
    K8S_NAMESPACE: $TEST_K8S_NAMESPACE
  tags:
    - family-manager
  dependencies: []

deploy:production:
  <<: *deploy_definition
  <<: *rules_production_definition
  variables:
    K8S_SERVER: $PROD_K8S_SERVER
    K8S_TOKEN: $PROD_K8S_TOKEN
    K8S_NAMESPACE: $PROD_K8S_NAMESPACE
  tags:
    - family-manager
  dependencies: []
