version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    links:
      - app
    volumes:
      - ./:${APP_CODE_PATH_CONTAINER}
  app:
    build:
      context: .
      dockerfile: docker/fpm.Dockerfile
    environment:
      SERVICE_NAME: app
      SERVICE_TAG: dev
    volumes:
      - ./:${APP_CODE_PATH_CONTAINER}
      - ./docker/php-fpm/php7.3.ini:/usr/local/etc/php/php.ini
    links:
      - postgres
  postgres:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    volumes:
      - ./docker/postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
